pool: Default

trigger:
  - master

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/Templates'
    inputs:
      SourceFolder: 'deployment'
      Contents: '*.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Templates'

  - task: Npm@1
    displayName: 'npm install production packages'
    inputs:
      command: 'install'
      workingDir: '$(System.DefaultWorkingDirectory)'
      verbose: false
      customCommand: '--production'

  - task: ArchiveFiles@2
    displayName: 'Archive source files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: 'drop'
      publishLocation: 'Container'